# Generated by Django 4.2.4 on 2023-08-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kls_api_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodel',
            name='set_template_file',
            field=models.FileField(upload_to='static/uploaded/set_templates'),
        ),
    ]
