# Generated by Django 4.2.4 on 2024-02-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kls_api_server', '0002_alter_setmodel_set_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodel',
            name='set_template',
            field=models.TextField(default='', null=True),
        ),
    ]
